AllCops:
  TargetRubyVersion: 2.5

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/MixedRegexpCaptureTypes:
  Enabled: false

Layout/LineLength:
  Max: 120